### ISSUE TITLE
I can confirm it works with the Xiaomi-Honeywell smoke detector

### ISSUE THREAD

**Issue by meetyg** [cadavre/miio_gateway#11]
Hey there!
You've done a great job of "hacking" the EU version of the gateway. I followed your instructions for installing the `miio_client` on my gateway, and using the component for HA, it works nicely.

I have the Xiaomi-Honeywell smoke detector, which I wasn't able to pair to the gateway using the Mi App (because the smoke detector is not meant for EU market).

I wanted to confirm that I have successfully paired the EU gateway with the smoke detector (identified as `lumi.sensor.smoke.v1`). 
It shows not only smoke detection state but also battery voltage and last time of heartbeat.

After putting gateway in Zigbee mode, I just pressed the button on the detector 3 times quickly and it paired.
In HA configuration I just added it as a sensor under the gateway using `class: smoke` and of course using sid found in HA logs after pairing.

Pretty cool I must say.
So I guess you can update the readme :-)

It would be nice if we could also configure the sensor using HA, for example to set its sensitivity (which can be set in Mi App but only if you paired it with a Chinese version gateway).

**Comment by cadavre** [comment]
Great news! Thanks for confirming! :) I should update the lib but always can't find a time. :/ Will do it finally and include this info, so keeping "issue" opened.

**Comment by cadavre** [comment]
Updated!
