### ISSUE TITLE
New HA version

### ISSUE THREAD

**Issue by grego1981** [cadavre/miio_gateway#21]
Hi and thank you for this invaluable integration!

During the last HA upgrade, this integration fails to load propably due to the new manifest requirement. Is it possible to make it work again??

Log entry:

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 8:46:10 AM (1 occurrences)
Last logged: 8:46:10 AM

Setup failed for miio_gateway: Integration not found.

**Comment by grego1981** [comment]
For anyone with the same issue, I created a manifest.json file according to the HA directives to bypass the requirments, it's a quick and dirty solution.

{
  "domain": "miio_gateway",
  "name": "miio_gateway",
  "documentation": "https://github.com/cadavre/miio_gateway",
  "dependencies": [],
  "codeowners": [],
  "requirements": [],
  "version": "0.2.2",
  "iot_class": "local_polling"
}

**Comment by cliffordwhansen** [comment]
@grego1981 I have created a PR #20

**Comment by cadavre** [comment]
Will merge #20 after #17 is confirmed.
