### ISSUE TITLE
Too lazy to make a PR, so just here

### ISSUE THREAD

**Issue by quarcko** [cadavre/miio_gateway#4]
Please fix this:
_LOGGER.debug()("Creating socket...")
to
_LOGGER.debug("Creating socket...")

Line 150 of init.py

:)

**Comment by quarcko** [comment]
Also line 431:

return self._gw._is_available
to
return self._gw._available

**Comment by quarcko** [comment]
Now ok, it is running, will report if something found, so far so good :)

**Comment by quarcko** [comment]
Nah, sorry one more thing: ping does not work:
TypeError: _ping() takes 1 positional argument but 2 were given

Your old version of ping had 2 arguments: (self, now)
Now "now" is missing... and also error.

**Comment by quarcko** [comment]
Also.....

 File "/config/custom_components/miio_gateway/__init__.py", line 270, in _ping
    time.sleep(6) # Give it `timeout` time to respond...
NameError: name 'time' is not defined

**Comment by cadavre** [comment]
Holy moly, I forgot to add final commit. My bad.

**Comment by cadavre** [comment]
Missing commit added.
