### ISSUE TITLE
Manual Probing of Sensors

### ISSUE THREAD

**Issue by grego1981** [cadavre/miio_gateway#6]
I have followed your suggestions and work and I can finally connect to my Xiamo gateway! I can see all the sensors but they seem to either not changing state or reamining in a false state (door is closed and HA shows it open) until their data are updated (that is when I get voltage, battery and such). Is there a way to trigger manualy the discovery of sensors?

**Comment by cadavre** [comment]
This is most likely to poor Zigbee signal. I'm facing to too with one door sensor being too far away from gateway. You can manually send a state from sensor to gateway by single-pressing button on your sensor. Don't press-and-hold or you gonna reset the assignment of sensor to gateway!

You can always turn on debugging log and see if event data is correct for your sensors with implementation from .py files.
